"""权限种子数据（部署时同步至 MySQL，管理员可覆盖名称/排序/显示）。"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

PermissionKind = Literal["catalog", "menu", "button", "api"]

ROLE_ADMIN = "admin"
ROLE_OPERATOR = "operator"
ROLE_VIEWER = "viewer"

# 租户 admin 租户域基线（tenant.* + 会话切换 + 个人中心）
TENANT_ADMIN_BASELINE_CODES: tuple[str, ...] = (
    "tenant.user.list",
    "tenant.user.create",
    "tenant.user.update",
    "tenant.user.enable",
    "tenant.user.assign_role",
    "tenant.role.list",
    "tenant.role.create",
    "tenant.role.update",
    "tenant.role.assign_permission",
    "tenant.permission.list",
    "tenant.dept.list",
    "tenant.dept.create",
    "tenant.dept.update",
    "tenant.dept.delete",
    "dev_param.list",
    "dev_param.update",
    "tenant.scheduled_job.list",
    "tenant.scheduled_job.trigger",
    "auth.switch_tenant",
    "auth.tenants",
    "menu.profile",
    "menu.tenant_scheduled_jobs",
    "user.profile.read",
    "user.profile.update",
    "user.profile.change_password",
    "user.profile.identity",
)


def tenant_self_service_codes() -> tuple[str, ...]:
    """租户内所有用户均应具备的个人中心权限。"""
    return (
        "menu.profile",
        "user.profile.read",
        "user.profile.update",
        "user.profile.change_password",
        "user.profile.identity",
    )


@dataclass(frozen=True, slots=True)
class PermissionSeed:
    """单条权限种子。"""

    code: str
    name: str
    kind: PermissionKind
    parent: str | None = None
    sort_order: int = 0
    route_path: str | None = None
    component_key: str | None = None
    api_codes: tuple[str, ...] = ()
    description: str = ""


def _s(
    code: str,
    name: str,
    kind: PermissionKind,
    *,
    parent: str | None = None,
    sort_order: int = 0,
    route_path: str | None = None,
    component_key: str | None = None,
    api_codes: tuple[str, ...] = (),
    description: str = "",
) -> PermissionSeed:
    return PermissionSeed(
        code=code,
        name=name,
        kind=kind,
        parent=parent,
        sort_order=sort_order,
        route_path=route_path,
        component_key=component_key,
        api_codes=api_codes,
        description=description,
    )


PERMISSION_SEEDS: tuple[PermissionSeed, ...] = (
    # 侧栏根目录默认序：设置 → 系统配置 → 平台管理（sync_rbac 每次同步目录名与 sort_order）
    _s("catalog.system", "系统配置", "catalog", sort_order=1),
    _s(
        "menu.users",
        "用户管理",
        "menu",
        parent="catalog.system",
        sort_order=0,
        route_path="/sys/users",
        component_key="users",
        api_codes=("system.user.list",),
    ),
    _s(
        "menu.roles",
        "角色管理",
        "menu",
        parent="catalog.system",
        sort_order=1,
        route_path="/sys/roles",
        component_key="roles",
        api_codes=("system.role.list",),
    ),
    _s(
        "menu.permissions",
        "权限管理",
        "menu",
        parent="catalog.system",
        sort_order=2,
        route_path="/sys/permissions",
        component_key="permissions",
        api_codes=("system.permission.list",),
    ),
    _s(
        "menu.audit",
        "审计日志",
        "menu",
        parent="catalog.system",
        sort_order=3,
        route_path="/sys/audit",
        component_key="audit",
        api_codes=("system.audit.read",),
    ),
    _s(
        "menu.scheduled_jobs",
        "定时任务",
        "menu",
        parent="catalog.system",
        sort_order=4,
        route_path="/sys/scheduled-jobs",
        component_key="scheduled_jobs",
        api_codes=("system.scheduled_job.list",),
    ),
    _s(
        "menu.sys_dev_params",
        "系统开发参数",
        "menu",
        parent="catalog.system",
        sort_order=5,
        route_path="/sys/dev-params",
        component_key="sys_dev_params",
        api_codes=("system.dev_param.list",),
    ),
    _s("catalog.platform", "平台管理", "catalog", sort_order=2),
    _s(
        "menu.orgs",
        "机构管理",
        "menu",
        parent="catalog.platform",
        sort_order=0,
        route_path="/sys/orgs",
        component_key="orgs",
        api_codes=("system.org.list",),
    ),
    _s(
        "system.org.update",
        "编辑机构",
        "button",
        parent="menu.orgs",
        sort_order=0,
    ),
    _s(
        "menu.tenants",
        "租户管理",
        "menu",
        parent="catalog.platform",
        sort_order=1,
        route_path="/sys/tenants",
        component_key="tenants",
        api_codes=("system.tenant.list",),
    ),
    _s(
        "system.tenant.update",
        "编辑租户",
        "button",
        parent="menu.tenants",
        sort_order=1,
    ),
    _s(
        "system.tenant.bind_role",
        "绑定系统角色",
        "button",
        parent="menu.tenants",
        sort_order=0,
    ),
    _s("catalog.tenant", "设置", "catalog", sort_order=0),
    _s(
        "menu.tenant_users",
        "用户管理",
        "menu",
        parent="catalog.tenant",
        sort_order=0,
        route_path="/users",
        component_key="users",
        api_codes=("tenant.user.list",),
    ),
    _s(
        "menu.tenant_roles",
        "角色管理",
        "menu",
        parent="catalog.tenant",
        sort_order=1,
        route_path="/roles",
        component_key="roles",
        api_codes=("tenant.role.list",),
    ),
    _s(
        "menu.depts",
        "部门管理",
        "menu",
        parent="catalog.tenant",
        sort_order=2,
        route_path="/depts",
        component_key="depts",
        api_codes=("tenant.dept.list",),
    ),
    _s(
        "menu.profile",
        "个人中心",
        "menu",
        parent="catalog.tenant",
        sort_order=3,
        route_path="/profile",
        component_key="profile",
        api_codes=(
            "user.profile.read",
            "user.profile.update",
            "user.profile.change_password",
            "user.profile.identity",
        ),
    ),
    _s(
        "menu.dev_params",
        "开发参数",
        "menu",
        parent="catalog.tenant",
        sort_order=4,
        route_path="/dev-params",
        component_key="dev_params",
        api_codes=("dev_param.list",),
    ),
    _s(
        "menu.tenant_scheduled_jobs",
        "定时任务",
        "menu",
        parent="catalog.tenant",
        sort_order=5,
        route_path="/scheduled-jobs",
        component_key="tenant_scheduled_jobs",
        api_codes=("tenant.scheduled_job.list",),
    ),
    _s(
        "tenant.scheduled_job.trigger",
        "执行定时任务",
        "button",
        parent="menu.tenant_scheduled_jobs",
        sort_order=0,
    ),
    _s(
        "dev_param.update",
        "保存开发参数",
        "button",
        parent="menu.dev_params",
        sort_order=0,
    ),
    _s(
        "system.user.create",
        "新建用户",
        "button",
        parent="menu.users",
        sort_order=0,
        api_codes=("system.role.list",),
    ),
    _s(
        "system.user.enable",
        "启用/禁用用户",
        "button",
        parent="menu.users",
        sort_order=1,
    ),
    _s(
        "system.user.reset_password",
        "重置密码",
        "button",
        parent="menu.users",
        sort_order=2,
    ),
    _s(
        "system.user.update",
        "编辑用户",
        "button",
        parent="menu.users",
        sort_order=3,
        api_codes=("system.role.list",),
    ),
    _s(
        "system.role.create",
        "新建角色",
        "button",
        parent="menu.roles",
        sort_order=0,
    ),
    _s(
        "system.role.assign_permission",
        "分配权限",
        "button",
        parent="menu.roles",
        sort_order=1,
    ),
    _s(
        "system.permission.create",
        "新建权限",
        "button",
        parent="menu.permissions",
        sort_order=0,
    ),
    _s(
        "system.permission.update",
        "编辑权限",
        "button",
        parent="menu.permissions",
        sort_order=1,
    ),
    _s(
        "system.permission.delete",
        "删除权限",
        "button",
        parent="menu.permissions",
        sort_order=2,
    ),
    _s(
        "system.audit.export",
        "导出审计日志",
        "button",
        parent="menu.audit",
        sort_order=0,
    ),
    _s(
        "system.scheduled_job.update",
        "编辑定时任务",
        "button",
        parent="menu.scheduled_jobs",
        sort_order=0,
    ),
    _s(
        "system.scheduled_job.trigger",
        "立即执行",
        "button",
        parent="menu.scheduled_jobs",
        sort_order=1,
    ),
    _s(
        "system.scheduled_job.control",
        "启停定时任务",
        "button",
        parent="menu.scheduled_jobs",
        sort_order=2,
    ),
    _s(
        "system.dev_param.update",
        "编辑系统开发参数",
        "button",
        parent="menu.sys_dev_params",
        sort_order=0,
    ),
    _s(
        "tenant.user.create",
        "新建用户",
        "button",
        parent="menu.tenant_users",
        sort_order=0,
        api_codes=("tenant.role.list",),
    ),
    _s(
        "tenant.user.enable",
        "启用/禁用用户",
        "button",
        parent="menu.tenant_users",
        sort_order=1,
    ),
    _s(
        "tenant.user.offboard",
        "离职",
        "button",
        parent="menu.tenant_users",
        sort_order=2,
    ),
    _s(
        "tenant.user.update",
        "编辑用户",
        "button",
        parent="menu.tenant_users",
        sort_order=3,
        api_codes=("tenant.role.list", "tenant.user.assign_role"),
    ),
    _s(
        "tenant.role.create",
        "新建角色",
        "button",
        parent="menu.tenant_roles",
        sort_order=0,
    ),
    _s(
        "tenant.role.assign_permission",
        "分配权限",
        "button",
        parent="menu.tenant_roles",
        sort_order=1,
        api_codes=("tenant.role.update",),
    ),
    _s("system.user.list", "用户列表", "api"),
    _s("system.user.assign_role", "分配用户角色", "api"),
    _s("system.role.list", "角色列表", "api"),
    _s("system.role.update", "编辑角色", "api"),
    _s("system.permission.list", "权限列表", "api"),
    _s("system.audit.read", "审计日志查询", "api"),
    _s("system.scheduled_job.list", "定时任务列表", "api"),
    _s("system.scheduled_job.read", "定时任务详情", "api"),
    _s("system.dev_param.list", "系统开发参数列表", "api"),
    _s("tenant.scheduled_job.list", "租户定时任务列表", "api"),
    _s("system.org.list", "机构列表", "api"),
    _s("system.org.create", "创建机构", "api"),
    _s("system.tenant.list", "租户列表", "api"),
    _s("system.tenant.create", "创建租户", "api"),
    _s("system.dept.list", "部门列表", "api"),
    _s("system.dept.create", "创建部门", "api"),
    _s("system.dept.update", "更新部门", "api"),
    _s("system.dept.delete", "删除部门", "api"),
    _s("auth.switch_tenant", "切换租户", "api"),
    _s("auth.tenants", "租户列表", "api"),
    _s("tenant.user.list", "租户用户列表", "api"),
    _s("tenant.user.assign_role", "分配租户用户角色", "api"),
    _s("tenant.role.list", "租户角色列表", "api"),
    _s("tenant.role.update", "更新租户角色", "api"),
    _s("tenant.permission.list", "租户权限树", "api"),
    _s("tenant.dept.list", "租户部门列表", "api"),
    _s("tenant.dept.create", "创建租户部门", "api"),
    _s("tenant.dept.update", "更新租户部门", "api"),
    _s("tenant.dept.delete", "删除租户部门", "api"),
    _s("user.profile.read", "个人资料读取", "api"),
    _s("user.profile.update", "个人资料更新", "api"),
    _s("user.profile.change_password", "修改密码", "api"),
    _s("user.profile.identity", "实名认证", "api"),
    _s("dev_param.list", "开发参数列表", "api"),
)

ASSIGNABLE_KINDS: frozenset[PermissionKind] = frozenset({"catalog", "menu", "button"})

API_ROUTE_SEEDS: tuple[tuple[str, str, str], ...] = (
    ("system.user.list", "GET", "/api/v1/users"),
    ("system.user.list", "GET", "/api/v1/users/*"),
    ("system.user.create", "POST", "/api/v1/users"),
    ("system.user.create", "GET", "/api/v1/users/tenant-options"),
    ("system.user.update", "PUT", "/api/v1/users/*"),
    ("system.user.update", "GET", "/api/v1/depts/tree-for-user"),
    ("system.user.reset_password", "POST", "/api/v1/users/*/reset-password"),
    ("system.user.enable", "PATCH", "/api/v1/users/*/enabled"),
    ("system.role.list", "GET", "/api/v1/roles"),
    ("system.role.list", "GET", "/api/v1/roles/*"),
    ("system.role.create", "POST", "/api/v1/roles"),
    ("system.role.update", "PUT", "/api/v1/roles/*"),
    ("system.role.assign_permission", "PUT", "/api/v1/roles/*/permissions"),
    ("system.permission.list", "GET", "/api/v1/permissions"),
    ("system.permission.list", "GET", "/api/v1/permissions/tree"),
    ("system.permission.list", "GET", "/api/v1/permissions/*"),
    ("system.permission.list", "GET", "/api/v1/permissions/*/bindings"),
    ("system.permission.create", "POST", "/api/v1/permissions"),
    ("system.permission.update", "PUT", "/api/v1/permissions/*"),
    ("system.permission.update", "PUT", "/api/v1/permissions/*/bindings"),
    ("system.permission.delete", "DELETE", "/api/v1/permissions/*"),
    ("system.audit.read", "GET", "/api/v1/audit/*"),
    ("system.audit.export", "POST", "/api/v1/audit/export"),
    ("system.scheduled_job.list", "GET", "/api/v1/scheduled-jobs"),
    ("system.scheduled_job.read", "GET", "/api/v1/scheduled-jobs/*"),
    ("system.scheduled_job.update", "PUT", "/api/v1/scheduled-jobs/*"),
    ("system.scheduled_job.list", "GET", "/api/v1/scheduled-jobs/tenant-options"),
    ("system.scheduled_job.trigger", "POST", "/api/v1/scheduled-jobs/*/trigger"),
    ("system.scheduled_job.control", "POST", "/api/v1/scheduled-jobs/*/start"),
    ("system.scheduled_job.control", "POST", "/api/v1/scheduled-jobs/*/stop"),
    ("system.dev_param.list", "GET", "/api/v1/sys/dev-params/*"),
    ("system.dev_param.update", "PUT", "/api/v1/sys/dev-params/*"),
    ("tenant.scheduled_job.list", "GET", "/api/v1/tenant/scheduled-jobs"),
    ("tenant.scheduled_job.trigger", "POST", "/api/v1/tenant/scheduled-jobs/*/trigger"),
    ("system.org.list", "GET", "/api/v1/orgs"),
    ("system.org.create", "POST", "/api/v1/orgs"),
    ("system.org.update", "PUT", "/api/v1/orgs/*"),
    ("system.tenant.list", "GET", "/api/v1/tenants"),
    ("system.tenant.list", "GET", "/api/v1/tenants/admin-user-options"),
    ("system.tenant.create", "POST", "/api/v1/tenants"),
    ("system.tenant.update", "PUT", "/api/v1/tenants/*"),
    ("system.tenant.bind_role", "GET", "/api/v1/tenants/*/system-roles"),
    ("system.tenant.bind_role", "PUT", "/api/v1/tenants/*/system-roles"),
    ("system.dept.list", "GET", "/api/v1/depts/tree"),
    ("system.dept.create", "POST", "/api/v1/depts"),
    ("system.dept.update", "PUT", "/api/v1/depts/*"),
    ("system.dept.delete", "DELETE", "/api/v1/depts/*"),
    ("auth.switch_tenant", "POST", "/api/v1/auth/switch-tenant"),
    ("auth.tenants", "GET", "/api/v1/auth/tenants"),
    ("tenant.user.list", "GET", "/api/v1/tenant/users"),
    ("tenant.user.list", "GET", "/api/v1/tenant/users/*"),
    ("tenant.user.create", "POST", "/api/v1/tenant/users"),
    ("tenant.user.update", "PUT", "/api/v1/tenant/users/*"),
    ("tenant.user.offboard", "POST", "/api/v1/tenant/users/*/offboard"),
    ("tenant.user.enable", "PATCH", "/api/v1/tenant/users/*/enabled"),
    ("tenant.user.assign_role", "PUT", "/api/v1/tenant/users/*"),
    ("tenant.role.list", "GET", "/api/v1/tenant/roles"),
    ("tenant.role.list", "GET", "/api/v1/tenant/roles/*"),
    ("tenant.role.create", "POST", "/api/v1/tenant/roles"),
    ("tenant.role.update", "PUT", "/api/v1/tenant/roles/*"),
    ("tenant.role.assign_permission", "PUT", "/api/v1/tenant/roles/*/permissions"),
    ("tenant.role.list", "GET", "/api/v1/tenant/roles/permissions/tree"),
    ("tenant.dept.list", "GET", "/api/v1/tenant/depts/tree"),
    ("tenant.dept.create", "POST", "/api/v1/tenant/depts"),
    ("tenant.dept.update", "PUT", "/api/v1/tenant/depts/*"),
    ("tenant.dept.delete", "DELETE", "/api/v1/tenant/depts/*"),
    ("user.profile.read", "GET", "/api/v1/users/me/profile"),
    ("user.profile.update", "PATCH", "/api/v1/users/me/profile"),
    ("user.profile.change_password", "POST", "/api/v1/users/me/change-password"),
    ("user.profile.identity", "POST", "/api/v1/users/me/identity"),
    ("dev_param.list", "GET", "/api/v1/dev-params/*"),
    ("dev_param.update", "PUT", "/api/v1/dev-params/*"),
)


def tenant_admin_baseline_codes() -> tuple[str, ...]:
    """租户 admin 固定基线：仅 tenant.*（平台 system.* 由 t_sys_user_roles 单独授予）。"""
    return TENANT_ADMIN_BASELINE_CODES


DEFAULT_ROLE_DEFS: dict[str, tuple[str, str, list[str]]] = {
    ROLE_ADMIN: ("管理员", "拥有全部权限", []),
    ROLE_OPERATOR: (
        "操作员",
        "租户业务读写",
        [
            "menu.tenant_users",
            "menu.tenant_roles",
            "menu.depts",
            "menu.profile",
            "menu.dev_params",
            "menu.tenant_scheduled_jobs",
            "tenant.user.create",
            "tenant.user.update",
            "tenant.user.enable",
            "tenant.role.create",
            "tenant.dept.create",
            "tenant.scheduled_job.trigger",
            "tenant.dept.update",
            "dev_param.update",
        ],
    ),
    ROLE_VIEWER: (
        "只读",
        "只读查看租户数据",
        [
            "menu.tenant_users",
            "menu.tenant_roles",
            "menu.depts",
            "menu.profile",
            "menu.tenant_scheduled_jobs",
        ],
    ),
}
